# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaltDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WaltDemo

#布局约束管理
  pod 'HandyJSON', '4.2.1'

#网络请求
  pod 'Alamofire', '4.8.2'

  pod 'web3swift.pod','2.1.10'	
  pod 'GTMBase64', '1.0.1'
  #标准加密库 
  pod 'CryptoSwift', '1.0.0'#'0.15.0'


end
